version: '{build}'

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
        - JAVA_HOME: C:\Program Files\Java\jdk11

build_script:
  - ./gradlew assemble --no-daemon
test_script:
  - ./gradlew check --no-daemon

on_success:
  - ./gradlew jacocoTestReport --no-daemon
  - ps: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
      .\codecov.exe -f build\reports\jacoco\test\jacocoTestReport.xml -F windows

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper