name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [8, 11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

      - name: Test
        env:
          GH_ACTIONS: true
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      - name: Build coverage report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoTestReport

      - uses: codecov/codecov-action@v3
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: LINUX
          fail_ci_if_error: false